ARG LANGUAGE_VERSION
FROM golang:${LANGUAGE_VERSION}-alpine AS builder

ARG APP_NAME="app"
ARG BUILD_FLAGS="NONE"
ARG STATIC_DIRS=""
ARG TARGET_ARCH="amd64"
ARG TARGET_OS="linux"
WORKDIR /app
COPY . .
ENV GOOS=${TARGET_OS}
ENV GOARCH=${TARGET_ARCH}
RUN go mod download && \
    if [ "$BUILD_FLAGS" = "NONE" ]; then \
        go build -o ${APP_NAME}; \
    else \
        go build ${BUILD_FLAGS} -o ${APP_NAME}; \
    fi


FROM alpine:3.21.3

WORKDIR /app
ARG APP_NAME=app

COPY --from=builder /app/${APP_NAME} /app/${APP_NAME}
COPY --from=builder /app/templates /app/templates
COPY --from=builder /app/static /app/static

RUN chmod +x /app/${APP_NAME}
EXPOSE 8080
CMD ["/app/app"]